Login/signup
rnpnull/SWE-Final-Project-The_Pegas pull request #14
Opened 2022-04-07 19:41 UTC by f-hash

Here is my new pull request

2022-04-07 22:30 UTC, rnpnull commented on backend/trivia_api/static/signup.html
> +<form action="/signup" class="form">
get rid of this file, we shouldnt have any frontend functionality pushed on our side, only API implementation

2022-04-07 22:32 UTC, rnpnull commented on backend/trivia_api/views.py
> +@login_manager.user_loader
this user loader is unnecessary, it's already in __init__, remove this

2022-04-07 22:33 UTC, rnpnull commented on frontend/src/logins /login.js
> +import React from 'react'
get rid of this file + containing folder, isn't going to be used

2022-04-07 22:33 UTC, rnpnull commented on backend/trivia_api/.gitignore
> +.env
this file is unnecessary? the .gitignore in the root folder has the same thing and it covers all subdirectory

2022-04-07 22:35 UTC, rnpnull commented on backend/trivia_api/views.py
> +@blueprint.route("/signup", methods=["GET", "POST"])
```suggestion
@blueprint.route("/signup", methods=["POST"])
```

no need to allow get in the first place

2022-04-07 22:36 UTC, rnpnull commented on backend/trivia_api/views.py
> +    if request.method == "POST":
```suggestion

```

take this if out after changing the decorator to only allow post

2022-04-07 22:38 UTC, rnpnull commented on backend/trivia_api/views.py
> +        data = request.get_json("password")
```suggestion
        data = request.get_json()
```

2022-04-07 22:39 UTC, rnpnull commented on backend/trivia_api/views.py
> +    return jsonify({"code": 400, "message": "failed"})  # what am I returning here
```suggestion
    
```

2022-04-07 22:43 UTC, rnpnull commented on backend/trivia_api/views.py
> +        newpass = User(password=passwords)
```suggestion
```

not sure what the goal was here,  but creating a User object requires a username and password, both strings. the way you pass these into the User later in the code is invalid, these dont need to be here

2022-04-07 22:44 UTC, rnpnull commented on backend/trivia_api/views.py
> +        passwords = generate_password_hash(newpasswords, method="sha256")
```suggestion
        username = data["username"]
        password = data["password"]
```

variable naming, no need to hash if a user isnt going to be made

2022-04-07 22:46 UTC, rnpnull commented on backend/trivia_api/views.py
> +        ):
```suggestion
        if not User.query.filter_by(username=username).first():
```

rewrite since the previous User objects are removed

also, you shouldnt check whether a user with the password exists; that would just disallow 2 people from having the same password which isnt what we want

2022-04-07 22:47 UTC, rnpnull commented on backend/trivia_api/views.py
> +            entry = User(username=newuser.username, password=newpass.password)
```suggestion
            new_user = User(username=username, password=generate_password_hash(password, method="sha256"))
```

variable naming/logic fix

2022-04-07 22:49 UTC, rnpnull commented on backend/trivia_api/views.py
> +            return jsonify({"code": 200, "message": "failed", "message": "success"})
no need to pass code, esp if 200, also the format I already have in place is to use success: True or if failure, False along with an error field
```suggestion
            return {"success": True}
```

2022-04-07 22:50 UTC, rnpnull commented on backend/trivia_api/views.py
> +            )
```suggestion
            return {"success": False, "error": "username already taken" }
```

2022-04-07 23:00 UTC, rnpnull commented on backend/trivia_api/views.py
> +    username = request.get_json("username")
```suggestion
    username = request.get_json()
```

2022-04-07 23:01 UTC, rnpnull commented on backend/trivia_api/views.py
> +    password = username["password"]
```suggestion
    username = data["username"]
    password = data["password"]
```

2022-04-07 23:02 UTC, rnpnull commented on backend/trivia_api/views.py
> +    user = User.query.filter_by(username=checkusers).first()
```suggestion
    user = User.query.filter_by(username=username).first()
```

2022-04-07 23:14 UTC, rnpnull commented on backend/trivia_api/views.py
> +    #         return redirect(url_for("blueprint.login"))
```suggestion
```

2022-04-07 23:14 UTC, rnpnull commented on backend/trivia_api/views.py
> +        )
```suggestion
        return {"success": False, "error": "invalid login"}
```

2022-04-07 23:14 UTC, rnpnull commented on backend/trivia_api/views.py
> +        return jsonify({"code": 200, "message": "failed", "message": "success"})
```suggestion
    login_user(user)
    return {"success": True}
```

else is unnecessary because of return from the if

2022-04-07 23:14 UTC, rnpnull commented on backend/trivia_api/views.py
> +    return jsonify({"message": "Success"})
```suggestion
    return {"success": True}
```

2022-04-07 23:59 UTC, rnpnull commented on backend/trivia_api/views.py
> +@blueprint.route("/login", methods=["GET", "POST"])
```suggestion
@blueprint.route("/login", methods=["POST"])
```

2022-04-08 00:01 UTC, rnpnull commented on backend/trivia_api/views.py
> +    return User.query.get(user_id)
u gotta remove this whole method not just the decorator

2022-04-08 00:04 UTC, rnpnull commented on backend/trivia_api/views.py
> +@blueprint.route("/logout", methods=["GET", "POST"])
just needs to be

`@blueprint.route("/logout")`

2022-04-08 00:05 UTC, rnpnull commented on backend/trivia_api/.gitignore
> +.env
delete this file

2022-04-08 01:19 UTC, f-hash commented
Changed the login/signup methods by rewriting the database logic and by making rewriting the signup logic to only accept acceptable JSON requests, and further deleted the load user methods and changed the logout method, In addition, fixing the merge conflicts between login/signup and main

2022-04-08 04:04 UTC, rnpnull requested changes

2022-04-08 18:40 UTC, rnpnull approved these changes

2022-04-08 18:54 UTC, merged